export const JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME';
export const JWT_SECRET_KEY = 'JWT_SECRET_KEY'
export const JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY'
export const JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME'
