#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Running pre-commit checks...${NC}"

npm run build
echo -e "${GREEN}Build is complete${NC}"


cd apps/ui/ &&
npm run lint
echo -e "${GREEN}Linter validation complete for the main project${NC}"

cd ../ && cd api/ &&
npm run lint
echo -e "${GREEN}Linter validation complete for the ui submodule${NC}"


echo -e "${GREEN}Pre-commit checks completed successfully.${NC}"

# Include E2E tests and unit tests

exit 0
